# data

# training parameters
gamma: 0.95
tau: 0.95
policy_htype: relu
policy_hsize: [512, 256]
policy_optimizer: "Adam"
policy_lr: 5.e-5
policy_momentum: 0.0
policy_weightdecay: 0.0
value_htype: relu
value_hsize: [512, 256]
value_optimizer: "Adam"
value_lr: 3.e-4
value_momentum: 0.0
value_weightdecay: 0.0
clip_epsilon: 0.2
min_batch_size: 50000
mini_batch_size: 32768
num_optim_epoch: 10
log_std: -2.3
fix_std: true
num_epoch: 30000
seed: 1
save_n_epochs: 100
reward_id: "world_rfc_implicit"
obs_type: "full"
actor_type: "mcp"
num_primitive: 8
action_v: 1
obs_v: 1
reactive_v: 1
reactive_rate: 0.3
sampling_temp: 0.2
has_shape: false

reward_weights:
  w_p: 0.3
  w_v: 0.1
  w_e: 0.45
  w_c: 0.1
  w_vf: 0.05

  k_p: 2.0
  k_v: 0.005
  k_e: 5.0
  k_c: 100.0
  k_vf: 1.0

data_specs:
  dataset_name: amass
  file_path: sample_data/amass_copycat_take5_train.pkl
  test_file_path: sample_data/amass_copycat_take5_test_small.pkl
  state_file_path: sample_data/amass_copycat_take3_states.pkl
  

  neutral_path: sample_data/standing_neutral.pkl
  flip_cnd: 0
  has_smpl_root: true
  traj_dim: 144
  t_min: 15
  t_max: 300
  nc: 2
  load_class: -1
  adaptive_iter: 200
  root_dim: 6
  flip_time: false
  mode: "all"
  base_rot: [0.7071, 0.7071, 0.0, 0.0]

# expert and environment
mujoco_model: humanoid_smpl_neutral_mesh
vis_model: humanoid_smpl_neutral_mesh_vis

env_episode_len: 100000
env_term_body: "body"
env_expert_trail_steps: 0
obs_coord: "root"
obs_phase: false

# RFC parameters
residual_force: true
residual_force_scale: 100.0
residual_force_mode: implicit

# other joint and body parameters
joint_params:
  # ["name", "k_p", "k_d", "a_ref", "a_scale", "torque_limit"]
  - ["L_Hip_z", 500.0, 50.0, 0.0, 1.0, 200.0]
  - ["L_Hip_y", 500.0, 50.0, 0.0, 1.0, 200.0]
  - ["L_Hip_x", 500.0, 50.0, 0.0, 1.0, 200.0]
  - ["L_Knee_z", 500.0, 50.0, 0.0, 1.0, 150.0]
  - ["L_Knee_y", 500.0, 50.0, 0.0, 1.0, 150.0]
  - ["L_Knee_x", 500.0, 50.0, 0.0, 1.0, 150.0]
  - ["L_Ankle_z", 400.0, 40.0, 0.0, 1.0, 100.0]
  - ["L_Ankle_y", 400.0, 40.0, 0.0, 1.0, 100.0]
  - ["L_Ankle_x", 400.0, 40.0, 0.0, 1.0, 100.0]
  - ["L_Toe_z", 200.0, 20.0, 0.0, 1.0, 100.0]
  - ["L_Toe_y", 200.0, 20.0, 0.0, 1.0, 100.0]
  - ["L_Toe_x", 200.0, 20.0, 0.0, 1.0, 100.0]
  - ["R_Hip_z", 500.0, 50.0, 0.0, 1.0, 200.0]
  - ["R_Hip_y", 500.0, 50.0, 0.0, 1.0, 200.0]
  - ["R_Hip_x", 500.0, 50.0, 0.0, 1.0, 200.0]
  - ["R_Knee_z", 500.0, 50.0, 0.0, 1.0, 150.0]
  - ["R_Knee_y", 500.0, 50.0, 0.0, 1.0, 150.0]
  - ["R_Knee_x", 500.0, 50.0, 0.0, 1.0, 150.0]
  - ["R_Ankle_z", 400.0, 40.0, 0.0, 1.0, 100.0]
  - ["R_Ankle_y", 400.0, 40.0, 0.0, 1.0, 100.0]
  - ["R_Ankle_x", 400.0, 40.0, 0.0, 1.0, 100.0]
  - ["R_Toe_z", 200.0, 20.0, 0.0, 1.0, 100.0]
  - ["R_Toe_y", 200.0, 20.0, 0.0, 1.0, 100.0]
  - ["R_Toe_x", 200.0, 20.0, 0.0, 1.0, 100.0]
  - ["Torso_z", 1000.0, 100.0, 0.0, 1.0, 200.0]
  - ["Torso_y", 1000.0, 100.0, 0.0, 1.0, 200.0]
  - ["Torso_x", 1000.0, 100.0, 0.0, 1.0, 200.0]
  - ["Spine_z", 1000.0, 100.0, 0.0, 1.0, 200.0]
  - ["Spine_y", 1000.0, 100.0, 0.0, 1.0, 200.0]
  - ["Spine_x", 1000.0, 100.0, 0.0, 1.0, 200.0]
  - ["Chest_z", 1000.0, 100.0, 0.0, 1.0, 200.0]
  - ["Chest_y", 1000.0, 100.0, 0.0, 1.0, 200.0]
  - ["Chest_x", 1000.0, 100.0, 0.0, 1.0, 200.0]
  - ["Neck_z", 100.0, 10.0, 0.0, 1.0, 50.0]
  - ["Neck_y", 100.0, 10.0, 0.0, 1.0, 50.0]
  - ["Neck_x", 100.0, 10.0, 0.0, 1.0, 50.0]
  - ["Head_z", 100.0, 10.0, 0.0, 1.0, 50.0]
  - ["Head_y", 100.0, 10.0, 0.0, 1.0, 50.0]
  - ["Head_x", 100.0, 10.0, 0.0, 1.0, 50.0]
  - ["L_Thorax_z", 400.0, 40.0, 0.0, 1.0, 100.0]
  - ["L_Thorax_y", 400.0, 40.0, 0.0, 1.0, 100.0]
  - ["L_Thorax_x", 400.0, 40.0, 0.0, 1.0, 100.0]
  - ["L_Shoulder_z", 400.0, 40.0, 0.0, 1.0, 100.0]
  - ["L_Shoulder_y", 400.0, 40.0, 0.0, 1.0, 100.0]
  - ["L_Shoulder_x", 400.0, 40.0, 0.0, 1.0, 100.0]
  - ["L_Elbow_z", 300.0, 30.0, 0.0, 1.0, 60.0]
  - ["L_Elbow_y", 300.0, 30.0, 0.0, 1.0, 60.0]
  - ["L_Elbow_x", 300.0, 30.0, 0.0, 1.0, 60.0]
  - ["L_Wrist_z", 100.0, 10.0, 0.0, 1.0, 50.0]
  - ["L_Wrist_y", 100.0, 10.0, 0.0, 1.0, 50.0]
  - ["L_Wrist_x", 100.0, 10.0, 0.0, 1.0, 50.0]
  - ["L_Hand_z", 100.0, 10.0, 0.0, 1.0, 50.0]
  - ["L_Hand_y", 100.0, 10.0, 0.0, 1.0, 50.0]
  - ["L_Hand_x", 100.0, 10.0, 0.0, 1.0, 50.0]
  - ["R_Thorax_z", 400.0, 40.0, 0.0, 1.0, 100.0]
  - ["R_Thorax_y", 400.0, 40.0, 0.0, 1.0, 100.0]
  - ["R_Thorax_x", 400.0, 40.0, 0.0, 1.0, 100.0]
  - ["R_Shoulder_z", 400.0, 40.0, 0.0, 1.0, 100.0]
  - ["R_Shoulder_y", 400.0, 40.0, 0.0, 1.0, 100.0]
  - ["R_Shoulder_x", 400.0, 40.0, 0.0, 1.0, 100.0]
  - ["R_Elbow_z", 300.0, 30.0, 0.0, 1.0, 60.0]
  - ["R_Elbow_y", 300.0, 30.0, 0.0, 1.0, 60.0]
  - ["R_Elbow_x", 300.0, 30.0, 0.0, 1.0, 60.0]
  - ["R_Wrist_z", 100.0, 10.0, 0.0, 1.0, 50.0]
  - ["R_Wrist_y", 100.0, 10.0, 0.0, 1.0, 50.0]
  - ["R_Wrist_x", 100.0, 10.0, 0.0, 1.0, 50.0]
  - ["R_Hand_z", 100.0, 10.0, 0.0, 1.0, 50.0]
  - ["R_Hand_y", 100.0, 10.0, 0.0, 1.0, 50.0]
  - ["R_Hand_x", 100.0, 10.0, 0.0, 1.0, 50.0]

body_params:
  # ["name","diff weight"]
  - ["L_Hip", 1.0]
  - ["L_Knee", 1.0]
  - ["L_Ankle", 1.0]
  - ["L_Toe", 0.0]
  - ["R_Hip", 1.0]
  - ["R_Knee", 1.0]
  - ["R_Ankle", 1.0]
  - ["R_Toe", 0.0]
  - ["Torso", 1.0]
  - ["Spine", 1.0]
  - ["Chest", 1.0]
  - ["Neck", 1.0]
  - ["Head", 1.0]
  - ["L_Thorax", 1.0]
  - ["L_Shoulder", 1.0]
  - ["L_Elbow", 1.0]
  - ["L_Wrist", 1.0]
  - ["L_Hand", 0.0]
  - ["R_Thorax", 1.0]
  - ["R_Shoulder", 1.0]
  - ["R_Elbow", 1.0]
  - ["R_Wrist", 1.0]
  - ["R_Hand", 0.0]
